version: '2'
services:
  server:
    build: .
    command: pm2-dev server/server.js
    environment:
      NODE_ENV: development
      NODE_APP_INSTANCE: ''
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules

  server2:
    build: .
    command: pm2-dev server/server.js
    environment:
      NODE_ENV: development
      NODE_APP_INSTANCE: ''
    depends_on:
      - mongodb
    ports:
      - "5001:5000"
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules

  nginx:
    image: nginx:1.13.11
    links:
      - server
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  mongodb:
    image: mongo:3.6.3
    command: mongod
    ports:
      - "27017:27017"

  redis-cache:
    image: redis
    container_name: cache
    expose:
      - 6379
  server-cache:
    build: ./redis
    volumes:
      - ./redis:/var/www/app
    links:
      - redis-cache
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis-cache://cache
      - NODE_ENV=development
      - PORT=3000
    command:
      sh -c 'npm i && node server.js'